apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kubernetesenterprise-enterprise-addons-pvc
  namespace: kubernetesenterprise
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  storageClassName: nfs-client
