apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kubernetesenterprise-filestore-pvc
  namespace: kubernetesenterprise
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: nfs-client
