apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: odoo-nfs-pvc
  namespace: odoo
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 25Gi
  storageClassName: nfs-client
