apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ printf "%s-filestore-pvc" .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.persistence.filestoreSize | default "5Gi" }}
  storageClassName: {{ .Values.persistence.storageClass | default "nfs-client" }}